### ISSUE TITLE
Compile error from overleaf

### ISSUE THREAD

**Issue by withtimesgo1115** [GandalfSaxe/laursens-xelatex-thesis-template#2]
Hi, thanks for your sharing but I met a problem when importing the zip file to the overleaf. It shows an error here and I don't know how to solve it. Could you have a look? Thank you!

![image](https://user-images.githubusercontent.com/56740244/116775216-289fa480-aa62-11eb-8eb5-a73b107923ed.png)

**Comment by gandalfsaxe** [comment]
Hi,

Sorry, the template was never tested to be uploaded into Overleaf. I did write my MSc Thesis with a partner, and we actually didn't have any problem collaborating with good old git via Github (https://github.com/gandalfsaxe/letomes), using Visual Studio Code and it worked great. We split up the work so that we rarely wrote on the same section, so conflicts weren't a problem. With a smaller project or paper, I can see Overleaf being useful. Or in a MSc or PhD project for that matter.

The advantage of Overleaf is the immediate sync and almost Google-Docs-like collaboration, which can be useful if collaborating with less technical persons or need to work on the same section as each other at the same time.

However I will highlight one aspect of working in git vs. Overleaf: You became much more conscious or what other people in the project are adding, removing and editing. Sure, you also have a history feature in Overleaf, but this history in typical online collaboration fashion, is like a continuous stream of changes that isn't really comprehensible if you want to know what changed recently / since you last looked in the document. And you really have to make an effort to check it, and probably won't in practice. Due to the nature of git, you have to pull changes, and can use online tools like GitHub and local tools [Kaleidoscope](https://kaleidoscope.app/) to always stay on top of what has changed recently from your collaborators, and give immediate feedback if necessary. Using git also means you have to active think about which bunch of changes logically constitutes a change and commit that change as one commit (i.e. we committed logical batches of changes, not just all the changes for a day in a commit called "changes").

Personally, I really appreciated being able to stay on top of other people's changes like this is a way I felt I wouldn't be able to with Overleaf (granted I haven't used it so much, and have only glanced their feature set, and they do try to offer something like a timeline, though I'm not too convinced). As mentioned, I think Overleaf is a fantastic tool that really have a place on some type of projects, but I just wanted to highlight some of the benefits of just working locally in git/github too.

Anyway I don't really have the time or the interest to fix these issues myself at this time. However I welcome any PRs that address the Overleaf issues if the changes to the template are minimal. Or perhaps a fork would be more appropriate, if the changes needed are substantial due to lack of support of some things on Overleaf's side. I suspect other people would want to try and use this template in Overleaf in the future, so the effort certainly wouldn't be wasted! :)

**Comment by withtimesgo1115** [comment]
Hi, @gandalfsaxe , thank you for your reply. I solved this problem by adjusting some settings in overleaf.
People who plan to use overleaf should modify compiler and main document here to match the template at first. 
I attached the figure here so anybody who don't know that could have a look. 

![image](https://user-images.githubusercontent.com/56740244/116853979-389cbd00-abf7-11eb-99ee-4d483c7d72d6.png)

**Comment by gandalfsaxe** [comment]
That's great. Did it solve it 100% or did you have to adjust other parts of the template?

**Comment by withtimesgo1115** [comment]
> That's great. Did it solve it 100% or did you have to adjust other parts of the template?

Yes, 100%. Your template can be used in overleaf too :)

**Comment by gandalfsaxe** [comment]
Excellent :) Closing then
